using System;
using System.Collections.Generic;
using System.Net.Sockets;
using Vector = MathNet.Numerics.LinearAlgebra.Vector<double>;

namespace MosaicLibary
{
    /// <summary>
    /// BlenderArm - Send off control values on a UDP port to a Blender arm model.
    /// </summary>
    /// <remarks>
    /// From the 12 values generated by our predictors, build 9, substantially by composing the
    /// DOFs of the wrist in pairs, e.g. wrist_flexion-wrist_extension. <br/>
    /// The order of the internal (received) prediction Vector, as defined in the cfg file, is:
    /// [ ThumbFlexion, ThumbRotation, Index, Middle, Ring, Little, wr_flex, wr_ext, wr_pron, wr_sup, wr_ulnar, wr_radial ]
    /// all values in [0,...,1] <br/>
    /// the order to be send to the Blender arm, as defined in 3DHands_left.py:
    /// [ ThumbFlexion, ThumbRotation, Index, Middle, Ring, Little, WristFlexionExtension, WristUlnarSupination, WirstUlnarPronation ]
    /// six values in [0,...,1] and three values in [-1,...,1]
    /// <list type="table">
    /// <item>
    /// <term>thumb flexion</term>
    /// <description>
    /// [0,1]
    /// </description>
    /// </item>
    /// <item>
    /// <term>thumb rotation</term>
    /// <description>
    /// [0,1]
    /// </description>
    /// </item>
    /// <item>
    /// <term>Index flexion</term>
    /// <description>
    /// [0,1]
    /// </description>
    /// </item>
    /// <item>
    /// <term>Middle flexion</term>
    /// <description>
    /// [0,1]
    /// </description>
    /// </item>
    /// <item>
    /// <term>Ring flexion</term>
    /// <description>
    /// [0,1]
    /// </description>
    /// </item>
    /// <item>
    /// <term>Little flexion</term>
    /// <description>
    /// [0,1]
    /// </description>
    /// </item>
    /// <item>
    /// <term>wrist flex ent</term>
    /// <description>
    /// [-1,1] (flex is -1, ext is 1)
    /// </description>
    /// </item>
    /// <item>
    /// <term>wrist uln rad</term>
    /// <description>
    /// [-1,1] (ulnar is -1, radial is 1)
    /// </description>
    /// </item>
    /// <item>
    /// <term>wrist sup pron</term>
    /// <description>
    /// [-1,1] (sup is -1, pron is 1)
    /// </description>
    /// </item>
    /// </list>
    /// for example,
    /// [1,1,1,1,1,1,0,0,0] is a fist with no wrist activation;
    ///[0,0,0,0,0,0,-1,0,1] is an open hand with flexed and pronated wrist.
    /// </remarks>
    /// 
    public class BlenderArm : Block
    {
        private UdpClient _udpClient = new UdpClient();
        private Vector _blenderArmCmd = Vector.Build.Dense(9);
        private Dictionary<DOAs, double> _actuationDict;

        /// <summary>
        /// Initializes a new instance of the BlenderArm class, setting up necessary configurations for UDP communication and input processing.
        /// </summary>
        /// <param name="Name">The name of this BlenderArm instance.</param>
        /// <param name="DesiredRate">The desired rate at which predictions are processed and control values are sent.</param>
        /// <param name="InputCfg">A list of configuration settings for input processing.</param>
        /// <param name="Params">Network parameters, specifically the host and port for UDP communication.</param>
        /// <param name="Path">The file path for additional configuration or resource files, if required.</param>  
        public BlenderArm(string Name, double DesiredRate, List<string> InputCfg, List<string> Params, string Path)
            : base(Name, DesiredRate, InputCfg, Params, Path) { }


        /// <summary>
        /// Configures the input sources for this BlenderArm instance. Validates the number of input blocks and parameters, and sets up the UDP client connection.
        /// </summary>
        /// <exception cref="Exception">Thrown if the number of input blocks is not exactly one or if the number of parameters is not exactly two (host and port).</exception>
        override public void ConfigureInputs()
        {
            base.ConfigureInputs();

            if (InputBlocks.Count != 1) throw new Exception($"BlenderArm {Name} must have one input block only.");
            DesiredRate = 0;

            // Params: host, port
            if (Params.Count != 2) throw new Exception($"BlenderArm {Name} must have 2 parameters.");

            _udpClient.Connect(Params[0], Convert.ToInt32(Params[1]));
        }

        /// <summary>
        /// Processes new input received from the connected input block and converts the prediction Vector into a command format understood by the Blender arm model for UDP transmission. This method transforms the received prediction Vector, consisting of degrees of actuation for various parts of the arm, into a format compatible with the Blender model's expectations, and sends the formatted command over UDP.
        /// </summary>
        /// <param name="sender">The block sending the input. This represents the source of the input data.</param>
        /// <param name="value">The input value, which is expected to be a dictionary mapping degrees of actuation (OldDOAs) to their predicted values. The dictionary keys represent different parts of the arm (e.g., thumb flexion, wrist extension), and the values are the predicted actuation strengths or positions, on a scale from 0 to 100.</param>
        /// <remarks>
        /// The method expects the input dictionary to contain specific keys corresponding to the OldDOAs defined by the enumeration. It maps these inputs to a 9-element Vector that aligns with the Blender arm model's input format. The mapping includes:
        /// - Scaling the values for thumb flexion, thumb rotation, Index, Middle, Ring, and Little finger positions from a [0, 100] range to [0, 1].
        /// - Converting wrist flexion/extension, ulnar/radial deviation, and supination/pronation values from a [0, 100] range to a [-1, 1] range, where necessary, to accommodate the model's expected input range for these motions.
        /// The final command is then sent as a string representation of the Vector over UDP to the specified host and port.
        /// </remarks>
        override protected void OnNewInput(Block sender, object value)
        {
            if (value is null) return;

            // the order of the internal (received) prediction Vector, as defined in the cfg file, is:
            // [ ThumbFlexion, ThumbRotation, Index, Middle, Ring, Little, wr_flex, wr_ext, wr_pron, wr_sup, wr_ulnar, wr_radial ]
            // all values in [0,...,1]
            _actuationDict = value as Dictionary<DOAs, double>;

            // the order to be send to the Blender arm, as defined in 3DHands_left.py:
            // [ ThumbFlexion, ThumbRotation, Index, Middle, Ring, Little, WristFlexionExtension, WristUlnarSupination, WirstUlnarPronation ]
            // six values in [0,...,1] and three values in [-1,...,1]
            _blenderArmCmd[0] = _actuationDict[DOAs.ThumbFlexion] / 100; // to map from [0,100] to [0,1]
            _blenderArmCmd[1] = _actuationDict[DOAs.ThumbRotation] / 100;
            _blenderArmCmd[2] = _actuationDict[DOAs.Index] / 100;
            _blenderArmCmd[3] = _actuationDict[DOAs.Middle] / 100;
            _blenderArmCmd[4] = _actuationDict[DOAs.Ring] / 100;
            _blenderArmCmd[5] = _actuationDict[DOAs.Little] / 100;
            _blenderArmCmd[6] = _actuationDict[DOAs.WristFlexionExtension] / 50 - 1; // to map from [0,100] to [-1,1]
            _blenderArmCmd[7] = _actuationDict[DOAs.WristUlnarRadialDevation] / 50 - 1;
            _blenderArmCmd[8] = -1*_actuationDict[DOAs.WristPronationSupination] / 50 - 1;

            // then send me off as a string, e.g. [1,1,1,1,1,1,0,0,0] which is a fist
            string sendString = $"[{Utils.Print(_blenderArmCmd)}]";
            _udpClient.SendAsync(System.Text.Encoding.ASCII.GetBytes(sendString), sendString.Length);
        }

        //double clipMe01(double v) { return Math.Max(0, Math.Min(1, v)); }
        //double clipMe11(double v) { return Math.Max(-1, Math.Min(1, v)); }
    }
}
